---
title: "Paper analysis"
output: 
  pdf_document: 
    extra_dependencies: ["graphicx", "threeparttable"]    
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: false
      smooth_scroll: false
      number_sections: true
editor_options: 
  chunk_output_type: console
header-includes:
  # - \usepackage[spanish,es-tabla,es-nodecimaldot]{babel}
  - \usepackage{times}           # Times New Roman
  - \usepackage{caption}
  - \captionsetup[figure, table]{labelfont={bf},labelformat={default},labelsep=period}
  - \usepackage{graphicx}
  - \usepackage{float}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}  
---

# Descriptivos

## Univariado
```{r echo=FALSE, results='asis',message=F}
pacman::p_load(dplyr, sjlabelled, summarytools, ggplot2, lme4, texreg, stargazer, car)
load("input/data-proc/data.rda")
st_css()
basereg <- data %>% 
  dplyr::select(
    igualdad.est,
    esp_publico.est,
    esp_privado.est,
    igualdad.pad,
    esp_publico.pad,
    esp_privado.pad,
    ap_discusion,
    c_civic,
    Sexo,
    num_fem,
    Educacion,
    quintiles_ingresos_pc_factor,
    Libros_apod_rec,
    dependencia,
    RBD,
    REGION
  ) %>% 
  ungroup() %>% 
  na.omit()

print(dfSummary(basereg,
               plain.ascii = FALSE,
               style = "grid",
               tmp.img.dir = "/tmp",
               graph.magnif = 0.75,
               headings = F,  # encabezado
               varnumbers = F, # num variable
               labels.col = T, # etiquetas
               na.col = F,    # missing
               graph.col = T, # plot
               valid.col = T, # n valido  
               # col.widths = c(5,5,10,10,10,10)
               ),
     method = "render")
```

## Bivariado
```{r}
pacman::p_load(summarytools,haven,sjPlot,dplyr)
load("input/data-proc/data.rda")
basereg <- data %>% 
  dplyr::select(
    igualdad.est,
    esp_publico.est,
    esp_privado.est,
    Sexo,
    ap_discusion,
    mean_discusion,
    num_fem,
    RBD,
    igualdad.pad,
    esp_publico.pad,
    esp_privado.pad,
    Educacion,
    Libros_apod,
    Libros_apod_rec,
    quintiles_ingresos_pc_factor,
    dependencia,
    REGION,
    c_civic,
  ) %>% na.omit()
```



# Modelos
```{r}
pacman::p_load(summarytools,haven,sjPlot,dplyr,lme4,haven,texreg,knitr,kableExtra,bda,lmerTest)
load("input/data-proc/data.rda")
data_proc <- data %>% dplyr::select(
  igualdad.est,
  esp_publico.est,
  esp_privado.est,
  Sexo,
  ap_discusion,
  mean_discusion,
  num_fem,
  RBD,
  igualdad.pad,
  esp_publico.pad,
  esp_privado.pad,
  Educacion,
  Libros_apod_rec,
  quintiles_ingresos_pc_factor,
  igualdad.pad_c,
  Educacion_c,
  igualdad.est_c,
  mean_ig_pad,
  mean_educacion,
  mean_ig_est,
  esp_publico.pad_c,
  esp_publico.est_c,
  mean_pub_pad,
  mean_pub_est,
  esp_privado.pad_c,
  esp_privado.est_c,
  mean_priv_pad,
  mean_priv_est,
  Libros_apod_c,
  Libros_apod,
  mean_libros_apod,
  dependencia,
  REGION,
  c_civic
) %>% as.data.frame() %>%  na.omit()

coef_names <- c(
          "Niña Ref. Niño)",
          "Conocimiento cívico",
          "Educación Media (Ref. 8vo básico o menos)",
          "Educación Técnica Superior (IP o CFT)",
          "Educación universitaria o Posgrado",
          "Entre 11 y 25 libros (Ref. Entre 0 y 10 libros)",
          "Entre 26 y 100 libros",
          "Más de 100 libros",
          "Quintil 2 (Ref. Quintil 1)",
          "Quintil 3",
          "Quintil 4",
          "Quintil 5",
          "No sabe / No responde"
          )
omit_coef <- "(dependencia)|(REGION)|(Intercept)|(quintiles_ingresos_pc_factorNs/Nr)"
footnote<- "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05 Controles son región de residencia (p>0.05) y dependencia administrativa de la escuela (p>0.05)"
scale_box <- 0.65
```


### Igualdad de derechos y oportunidades
```{r}
reg_igualdad1 <- lmer(igualdad.est ~ 1 + Sexo + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad2 <- lmer(igualdad.est ~ 1 + c_civic + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad3 <- lmer(igualdad.est ~ 1 + factor(Educacion) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad4 <- lmer(igualdad.est ~ 1 + factor(Libros_apod_rec) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad5 <- lmer(igualdad.est ~ 1 + factor(quintiles_ingresos_pc_factor) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad6 <- lmer(igualdad.est ~ 1 + igualdad.pad + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad7 <- lmer(igualdad.est ~ 1 + ap_discusion + mean_discusion + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad8 <- lmer(igualdad.est ~ 1 + num_fem + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_igualdad9 <- lmer(igualdad.est ~ 1 + Sexo + factor(Educacion) + factor(Libros_apod_rec) + factor(quintiles_ingresos_pc_factor) + igualdad.pad + ap_discusion + mean_discusion + num_fem + factor(dependencia) + factor(REGION) + c_civic + (1 | RBD), data=data_proc)
```
```{r, results='asis'}
caption <- "Modelo de regresión multiniveo para Igualdad de derechos y oportunidades"
knitreg(list(reg_igualdad1,reg_igualdad2,reg_igualdad3,reg_igualdad4,
             reg_igualdad5,reg_igualdad6,reg_igualdad7,reg_igualdad8,reg_igualdad9),
        custom.model.names = c("Modelo 1",  "Modelo 2",  "Modelo 3",  "Modelo 4",  
                               "Modelo 5",  "Modelo 6",  "Modelo 7",  "Modelo 8",  "Modelo 9"),
        custom.note = footnote,
        omit.coef = omit_coef, 
        custom.coef.names = c(coef_names,
          "Actitudes igualdad de derechos (apod.)",
          "Apertura a la discusión (individual)",
          "Apertura a la discusión (promedio)",
          "Proporción de niñas en el aula"
        ),
       scalebox = scale_box,
       threeparttable = F,
       caption.above = T,
       caption=caption
       )
```
### Distribución igualitaria de roles en la esfera pública
```{r}
reg_esp.pub1 <- lmer(esp_publico.est ~ 1 + Sexo + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub2 <- lmer(esp_publico.est ~ 1 + c_civic + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub3 <- lmer(esp_publico.est ~ 1 + factor(Educacion) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub4 <- lmer(esp_publico.est ~ 1 + factor(Libros_apod_rec) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub5 <- lmer(esp_publico.est ~ 1 + factor(quintiles_ingresos_pc_factor) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub6 <- lmer(esp_publico.est ~ 1 + esp_publico.pad + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub7 <- lmer(esp_publico.est ~ 1 + ap_discusion + mean_discusion + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub8 <- lmer(esp_publico.est ~ 1 + num_fem + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.pub9 <- lmer(esp_publico.est ~ 1 + Sexo + factor(Educacion) + factor(Libros_apod_rec) + factor(quintiles_ingresos_pc_factor) + esp_publico.pad + ap_discusion + mean_discusion + num_fem + factor(dependencia) + factor(REGION) + c_civic + (1 | RBD), data=data_proc)
#screenreg(list(reg_esp.pub1,reg_esp.pub2,reg_esp.pub3,reg_esp.pub4,reg_esp.pub5,reg_esp.pub6,reg_esp.pub7,reg_esp.pub8,reg_esp.pub9))
```
```{r,results='asis'}
caption <- "Modelo de regresión multiniveo para Distribución igualitaria de roles en la esfera pública"
knitreg(list(reg_esp.pub1,reg_esp.pub2,reg_esp.pub3,reg_esp.pub4,reg_esp.pub5,reg_esp.pub6,reg_esp.pub7,reg_esp.pub8,reg_esp.pub9), 
        custom.model.names = c("Modelo 1","Modelo 2","Modelo 3","Modelo 4","Modelo 5","Modelo 6","Modelo 7","Modelo 8","Modelo 9"), 
        custom.note = footnote,
        omit.coef = omit_coef, 
        custom.coef.names = c(coef_names,
          "Actitudes igualdad de derechos (apod.)",
          "Apertura a la discusión (individual)",
          "Apertura a la discusión (promedio)",
          "Proporción de niñas en el aula"
        ),
        scalebox = scale_box,
        threeparttable = F,
        caption.above = T,
        caption=caption
        )
```
### Distribución igualitaria de roles en la esfera privada
```{r}
reg_esp.priv1 <- lmer(esp_privado.est ~ 1 + Sexo + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv2 <- lmer(esp_privado.est ~ 1 + c_civic + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv3 <- lmer(esp_privado.est ~ 1 + factor(Educacion) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv4 <- lmer(esp_privado.est ~ 1 + factor(Libros_apod_rec) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv5 <- lmer(esp_privado.est ~ 1 + factor(quintiles_ingresos_pc_factor) + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv6 <- lmer(esp_privado.est ~ 1 + esp_privado.pad + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv7 <- lmer(esp_privado.est ~ 1 + ap_discusion + mean_discusion + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv8 <- lmer(esp_privado.est ~ 1 + num_fem + factor(dependencia) + factor(REGION) + (1 | RBD), data=data_proc)
reg_esp.priv9 <- lmer(esp_privado.est ~ 1 + Sexo + factor(Educacion) + factor(Libros_apod_rec) + factor(quintiles_ingresos_pc_factor) + esp_privado.pad + ap_discusion + mean_discusion + num_fem + factor(dependencia) + factor(REGION) + c_civic + (1 | RBD), data=data_proc)
```
```{r,results='asis'}
caption <- "Modelo de regresión multinivel Distribución igualitaria de roles en la esfera privada"
knitreg(list(reg_esp.priv1,reg_esp.priv2,reg_esp.priv3,reg_esp.priv4,reg_esp.priv5,reg_esp.priv6,reg_esp.priv7,reg_esp.priv8,reg_esp.priv9), 
        custom.model.names = c("Modelo 1","Modelo 2","Modelo 3","Modelo 4","Modelo 5","Modelo 6","Modelo 7","Modelo 8","Modelo 9"),
        custom.note = footnote,
        omit.coef = omit_coef, 
        custom.coef.names = c(coef_names,
          "Actitudes igualdad de derechos (apod.)",
          "Apertura a la discusión (individual)",
          "Apertura a la discusión (promedio)",
          "Proporción de niñas en el aula"
        ),
        scalebox = scale_box,
        threeparttable = F,
        caption.above = T,
        caption=caption
        )
```

```{r}
### Igualdad de derechos y oportunidades
reg_igual1E <- lmer(igualdad.pad ~ 1 + factor(Educacion) + (1 | RBD), data=data_proc) # Efecto al mediador
sreg_igual1E <- summary(reg_igual1E)
reg_igual2E <- lmer(igualdad.est ~ 1 + factor(Educacion) + (1 | RBD), data=data_proc) # Efecto Total
sreg_igual2E <- summary(reg_igual2E)
reg_igual3E <- lmer(igualdad.est ~ 1 + igualdad.pad + (1 | RBD), data=data_proc) # Efecto del mediador
reg_igual4E <- lmer(igualdad.est ~ 1 + factor(Educacion) + igualdad.pad + (1 | RBD), data=data_proc) # Efecto directo + mediado (del*al)
sreg_igual4E <- summary(reg_igual4E)
reg_igual1L <- lmer(igualdad.pad ~ 1 + factor(Libros_apod_rec) + (1 | RBD), data=data_proc)
reg_igual2L <- lmer(igualdad.est ~ 1 + factor(Libros_apod_rec) + (1 | RBD), data=data_proc)
sreg_igual2L <- summary(reg_igual2L)
reg_igual3L <- lmer(igualdad.est ~ 1 + esp_publico.pad + (1 | RBD), data=data_proc)
reg_igual4L <- lmer(igualdad.est ~ 1 + factor(Libros_apod_rec) + igualdad.pad + (1 | RBD), data=data_proc)
sreg_igual4L <- summary(reg_igual4L)
reg_igual1Q <- lmer(igualdad.pad ~ 1 + factor(quintiles_ingresos_pc_factor) + (1 | RBD), data=data_proc)
reg_igual2Q <- lmer(igualdad.est ~ 1 + factor(quintiles_ingresos_pc_factor) + (1 | RBD), data=data_proc)
sreg_igual2Q <- summary(reg_igual2Q)
reg_igual3Q <- lmer(igualdad.est ~ 1 + esp_publico.pad + (1 | RBD), data=data_proc)
reg_igual4Q <- lmer(igualdad.est ~ 1 + factor(quintiles_ingresos_pc_factor) + igualdad.pad + (1 | RBD), data=data_proc)
sreg_igual4Q <- summary(reg_igual4Q)
### Espacio publico
reg_esp.pub1E <- lmer(esp_publico.pad ~ 1 + factor(Educacion) + (1 | RBD), data=data_proc)
reg_esp.pub2E <- lmer(esp_publico.est ~ 1 + factor(Educacion) + (1 | RBD), data=data_proc)
sreg_esp.pub2E <- summary(reg_esp.pub2E)
reg_esp.pub3E <- lmer(esp_publico.est ~ 1 + esp_publico.pad + (1 | RBD), data=data_proc)
reg_esp.pub4E <- lmer(esp_publico.est ~ 1 + factor(Educacion) + esp_publico.pad + (1 | RBD), data=data_proc)
sreg_esp.pub4E <- summary(reg_esp.pub4E)
reg_esp.pub1L <- lmer(esp_publico.pad ~ 1 + factor(Libros_apod_rec) + (1 | RBD), data=data_proc)
reg_esp.pub2L <- lmer(esp_publico.est ~ 1 + factor(Libros_apod_rec) + (1 | RBD), data=data_proc)
sreg_esp.pub2L <- summary(reg_esp.pub2L)
reg_esp.pub3L <- lmer(esp_publico.est ~ 1 + esp_publico.pad + (1 | RBD), data=data_proc)
reg_esp.pub4L <- lmer(esp_publico.est ~ 1 + factor(Libros_apod_rec) + esp_publico.pad + (1 | RBD), data=data_proc)
sreg_esp.pub4L <- summary(reg_esp.pub4L)
reg_esp.pub1Q <- lmer(esp_publico.pad ~ 1 + factor(quintiles_ingresos_pc_factor) + (1 | RBD), data=data_proc)
reg_esp.pub2Q <- lmer(esp_publico.est ~ 1 + factor(quintiles_ingresos_pc_factor) + (1 | RBD), data=data_proc)
sreg_esp.pub2Q <- summary(reg_esp.pub2Q)
reg_esp.pub3Q <- lmer(esp_publico.est ~ 1 + esp_publico.pad + (1 | RBD), data=data_proc)
reg_esp.pub4Q <- lmer(esp_publico.est ~ 1 + factor(quintiles_ingresos_pc_factor) + esp_publico.pad + (1 | RBD), data=data_proc)
sreg_esp.pub4Q <- summary(reg_esp.pub4Q)
### Espacio privado
reg_esp.priv1E <- lmer(esp_privado.pad ~ 1 + factor(Educacion) + (1 | RBD), data=data_proc)
reg_esp.priv2E <- lmer(esp_privado.est ~ 1 + factor(Educacion) + (1 | RBD), data=data_proc)
sreg_esp.priv2E <- summary(reg_esp.priv2E)
reg_esp.priv3E <- lmer(esp_privado.est ~ 1 + esp_privado.pad + (1 | RBD), data=data_proc)
reg_esp.priv4E <- lmer(esp_privado.est ~ 1 + factor(Educacion) + esp_privado.pad + (1 | RBD), data=data_proc)
sreg_esp.priv4E <- summary(reg_esp.priv4E)
reg_esp.priv1L <- lmer(esp_privado.pad ~ 1 + factor(Libros_apod_rec) + (1 | RBD), data=data_proc)
reg_esp.priv2L <- lmer(esp_privado.est ~ 1 + factor(Libros_apod_rec) + (1 | RBD), data=data_proc)
sreg_esp.priv2L <- summary(reg_esp.priv2L)
reg_esp.priv3L <- lmer(esp_privado.est ~ 1 + esp_privado.pad + (1 | RBD), data=data_proc)
reg_esp.priv4L <- lmer(esp_privado.est ~ 1 + factor(Libros_apod_rec) + esp_privado.pad + (1 | RBD), data=data_proc)
sreg_esp.priv4L <- summary(reg_esp.priv4L)
reg_esp.priv1Q <- lmer(esp_privado.pad ~ 1 + factor(quintiles_ingresos_pc_factor) + (1 | RBD), data=data_proc)
reg_esp.priv2Q <- lmer(esp_privado.est ~ 1 + factor(quintiles_ingresos_pc_factor) + (1 | RBD), data=data_proc)
sreg_esp.priv2Q <- summary(reg_esp.priv2Q)
reg_esp.priv3Q <- lmer(esp_privado.est ~ 1 + esp_privado.pad + (1 | RBD), data=data_proc)
reg_esp.priv4Q <- lmer(esp_privado.est ~ 1 + factor(quintiles_ingresos_pc_factor) + esp_privado.pad + (1 | RBD), data=data_proc)
sreg_esp.priv4Q <- summary(reg_esp.priv4Q)
### Test de Sobel
iE1_E4<-mediation.test(data_proc$igualdad.pad,data_proc$Educacion,data_proc$igualdad.est)
iL1_L4<-mediation.test(data_proc$igualdad.pad,data_proc$Libros_apod,data_proc$igualdad.est)
iQ1_Q4<-mediation.test(data_proc$igualdad.pad,data_proc$quintiles_ingresos_pc_factor,data_proc$igualdad.est)
puE1_E4<-mediation.test(data_proc$esp_publico.pad,data_proc$Educacion,data_proc$esp_publico.est)
puL1_L4<-mediation.test(data_proc$esp_publico.pad,data_proc$Libros_apod,data_proc$esp_publico.est)
puQ1_Q4<-mediation.test(data_proc$esp_publico.pad,data_proc$quintiles_ingresos_pc_factor,data_proc$esp_publico.est)
prE1_E4<-mediation.test(data_proc$esp_privado.pad,data_proc$Educacion,data_proc$esp_privado.est)
prL1_L4<-mediation.test(data_proc$esp_privado.pad,data_proc$Libros_apod,data_proc$esp_privado.est)
prQ1_Q4<-mediation.test(data_proc$esp_privado.pad,data_proc$quintiles_ingresos_pc_factor,data_proc$esp_privado.est)
```
### Tabla de mediaciones
```{r echo=FALSE, results='asis'}
table_format = if(is_html_output()) {
  "html"
} else if(is_latex_output()) {
  "latex"
}


data_proc$Educacion <- 
  factor(data_proc$Educacion, 
         levels = c(1,2,3,4), 
         labels = c("Educación Básica", "Educación Media (Ref. 8vo Básico)", "Educación Téc.Superior (IP o CFT)", "Universidad o Posgrado"))
data_proc$Libros_apod_rec <- 
  factor(data_proc$Libros_apod_rec, 
         levels = c(1,2,3,4), 
         labels = c("Entre 0 y 10 libros", "Entre 11 y 25 libros (Ref. Entre 0 y 10 libros)", "Entre 26 y 100 libros", "Más de 100 libros"))
data_proc$quintiles_ingresos_pc_factor <- 
  factor(data_proc$quintiles_ingresos_pc_factor, 
         levels = c(1,2,3,4,5,99), 
         labels = c("Quintil 1", "Quintil 2 (Ref. Quintil 1)", "Quintil 3", "Quintil 4", "Quintil 5", "Ns/Nr"))

 collapse_rows_dt <- data.frame(Variable = c(rep("Educación de los padres", 3), rep("Cantidad de libros", 3), rep("Quintiles de ingreso",5)),
                    Categorias = c(sjlabelled::get_labels(data_proc$Educacion)[-1],
                                   sjlabelled::get_labels(data_proc$Libros_apod_rec)[-1],
                                   sjlabelled::get_labels(data_proc$quintiles_ingresos_pc_factor)[-1]),
                   
                     Efectos_Directos = c(paste0(round(reg_igual4E@beta[2:4],3),gtools::stars.pval(sreg_igual4E$coefficients[2:4,5])),
                                         paste0(round(reg_igual4L@beta[2:4],3),gtools::stars.pval(sreg_igual4L$coefficients[2:4,5])),
                                         paste0(round(reg_igual4Q@beta[2:6],3),gtools::stars.pval(sreg_igual4Q$coefficients[2:6,5]))),
                    Efectos_Indirectos = c(
                                           paste0(round(reg_igual1E@beta[2:4]*reg_igual4E@beta[5],3),gtools::stars.pval(iE1_E4[2,1])),
                                           paste0(round(reg_igual1L@beta[2:4]*reg_igual4L@beta[4],3),   gtools::stars.pval(iL1_L4[2,1])),
                                           paste0(round(reg_igual1Q@beta[2:6]*reg_igual4Q@beta[7],3), gtools::stars.pval(iQ1_Q4[2,1]))
                                           ),
                    Efectos_Totales =  c(
                                         paste0(round(reg_igual2E@beta[2:4],3),gtools::stars.pval(sreg_igual2E$coefficients[2:4,5])),
                                         paste0(round(reg_igual2L@beta[2:4],3),gtools::stars.pval(sreg_igual2L$coefficients[2:4,5])),
                                         paste0(round(reg_igual2Q@beta[2:6],3),gtools::stars.pval(sreg_igual2Q$coefficients[2:6,5]))
                                         ),
                    Porcentaje_Indirecto = c(
                                             paste(round(reg_igual1E@beta[2:4]*reg_igual4E@beta[5]*100/reg_igual2E@beta[2:4],1),"%"),
                                             paste(round(reg_igual1L@beta[2:4]*reg_igual4L@beta[4]*100/reg_igual2L@beta[2:4],1),"%"),
                                             paste(round(reg_igual1Q@beta[2:6]*reg_igual4Q@beta[7]*100/reg_igual2Q@beta[2:6],1),"%")
                                             ),
                   
 
                    Efectos_Directos = c(
                                         paste0(round(reg_esp.pub4E@beta[2:4],3),gtools::stars.pval(sreg_esp.pub4E$coefficients[2:4,5])),
                                         paste0(round(reg_esp.pub4L@beta[2:4],3), gtools::stars.pval(sreg_esp.pub4L$coefficients[2:4,5])),
                                         paste0(round(reg_esp.pub4Q@beta[2:6],3), gtools::stars.pval(sreg_esp.pub4Q$coefficients[2:6,5]))
                                          )
                                         
                                         ,
                   
                   
                    Efectos_Indirectos = c(
                                          paste0(round(reg_esp.pub1E@beta[2:4]*reg_esp.pub4E@beta[5],3),gtools::stars.pval(puE1_E4[2,1])),
                                           paste0(round(reg_esp.pub1L@beta[2:4]*reg_esp.pub4L@beta[4],3), gtools::stars.pval(puL1_L4[2,1])),
                                           paste0(round(reg_esp.pub1Q@beta[2:6]*reg_esp.pub4Q@beta[7],3),gtools::stars.pval(puQ1_Q4[2,1]))),
                   
                   
                   
                    Efectos_Totales =  c(
                                          paste0(round(reg_esp.pub2E@beta[2:4],3),gtools::stars.pval(sreg_esp.pub2E$coefficients[2:4,5])),
                                         paste0(round(reg_esp.pub2L@beta[2:4],3),gtools::stars.pval(sreg_esp.pub2L$coefficients[2:4,5])),
                                         paste0(round(reg_esp.pub2Q@beta[2:6],3),gtools::stars.pval(sreg_esp.pub2Q$coefficients[2:6,5]))
                                         ),
                   
                   
                    Porcentaje_Indirecto = c(paste(round(reg_esp.pub1E@beta[2:4]*reg_esp.pub4E@beta[5]*100/reg_esp.pub2E@beta[2:4],1),"%"),
                                             paste(round(reg_esp.pub1L@beta[2:4]*reg_esp.pub4L@beta[4]*100/ reg_esp.pub2L@beta[2:4],1),"%"),                   paste(round(reg_esp.pub1Q@beta[2:6]*reg_esp.pub4Q@beta[7]*100/reg_esp.pub2Q@beta[2:6],1),"%")),
                   
 
                    Efectos_Directos = c(
                                         paste0(round(reg_esp.priv4E@beta[2:4],3), gtools::stars.pval(sreg_esp.priv4E$coefficients[2:4,5])),
                                         paste0(round(reg_esp.priv4L@beta[2:4],3),gtools::stars.pval(sreg_esp.priv4L$coefficients[2:4,5])),
                                         paste0(round(reg_esp.priv4Q@beta[2:6],3),gtools::stars.pval(sreg_esp.priv4Q$coefficients[2:6,5]))),
                   
 
 
                   Efectos_Indirectos = c(paste0(round(reg_esp.priv1E@beta[2:4]*reg_esp.priv4E@beta[5],3), gtools::stars.pval(prE1_E4[2,1])),
                                           paste0(round(reg_esp.priv1L@beta[2:4]*reg_esp.priv4L@beta[4],3),gtools::stars.pval(prL1_L4[2,1])),
                                           paste0(round(reg_esp.priv1Q@beta[2:6]*reg_esp.priv4Q@beta[7],3),gtools::stars.pval(prQ1_Q4[2,1]))),
                 
                    Efectos_Totales = c(
                                        paste0(round(reg_esp.priv2E@beta[2:4],3),gtools::stars.pval(sreg_esp.priv2E$coefficients[2:4,5])),
                                        paste0(round(reg_esp.priv2L@beta[2:4],3),gtools::stars.pval(sreg_esp.priv2L$coefficients[2:4,5])),
                                        paste0(round(reg_esp.priv2Q@beta[2:6],3),gtools::stars.pval(sreg_esp.priv2Q$coefficients[2:6,5]))
                                      ),
                   Porcentaje_Indirecto = c(paste(round(reg_esp.priv1E@beta[2:4]*reg_esp.priv4E@beta[5]*100/reg_esp.priv2E@beta[2:4],1),"%"),
  paste(round(reg_esp.priv1L@beta[2:4]*reg_esp.priv4L@beta[4]*100/ reg_esp.priv2L@beta[2:4],1),"%"),
  paste(round(reg_esp.priv1Q@beta[2:6]*reg_esp.priv4Q@beta[7]*100/reg_esp.priv2Q@beta[2:6],1),"%")))
 
  kable(collapse_rows_dt, align = "llcccccccccccc",format = table_format,booktabs=T, col.names = c(
   "Variable",
   "Categorías",
   "Efectos Directos",
   "Efectos Indirectos",
   "Efectos Totales",
   "% de Efectos Indirectos",
   "Efectos Directos",
   "Efectos Indirectos",
   "Efectos Totales",
   "% de Efectos Indirectos",
   "Efectos Directos",
   "Efectos Indirectos",
   "Efectos Totales",
   "% de Efectos Indirectos"
 )) %>%
 add_header_above(c(" " = 2,
                    "Igualdad de derechos y oportunidades"=4,
                    "Distribución igualitaria de roles en la esfera pública"=4,
                    "Distribución igualitaria de roles en la esfera privada"=4), bold = T)%>%
   kable_paper("hover",full_width = F,latex_options = c("scale_down")) %>%
    column_spec(1, bold = T,width = "1.5cm") %>%
    column_spec(3:14, width = "1.5cm") %>%
    collapse_rows(columns = 1:2, valign = "top") %>% 
    landscape()
```

