---
title: "Análisis de mediacion"
author: "Daniel Miranda, Julio Iturra, Anaís Herrera y Kevin Carrasco"
date: "24-05-2021"
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
    css: "../input/css/custom.css"
  pdf_document: default
---

### Mediaciones paquete mediation


```{r setup}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
```

```{r}
pacman::p_load(stargazer, ggplot2, sjmisc, car, sjlabelled, haven, cowplot,
               sjPlot, summarytools, kableExtra, corrplot, coefplot, ltm,
               polycor,psych, lme4, ppcor, texreg, skimr, gtools, bda, 
               lmerTest, Matrix, extrafont, sessioninfo, dplyr,mediation,
               fastDummies,gtools)
load("../input/data-proc/data.rda")
data_proc=data %>% 
  dplyr::select(
    igualdad.est,
    esp_publico.est,
    esp_privado.est,
    Sexo,
    ap_discusion,
    mean_discusion,
    num_fem,
    RBD,
    igualdad.pad,
    esp_publico.pad,
    esp_privado.pad,
    Educacion,
    Libros_apod,
    Libros_apod_rec,
    quintiles_ingresos_pc_factor,
    dependencia,
    REGION,
    c_civic
  ) %>% as.data.frame() 
data_proc <- na.omit(data_proc)
```


#### Igualdad de derechos y oportunidades
```{r}
data_proc$Educacion <- factor(data_proc$Educacion, 
                              levels = c("8vo básico o menos", 
                                         "Educación Media", 
                                         "Educación Téc.Superior", 
                                         "Universidad o Posgrado"),
                              labels = c("ed_basica", "ed_media", 
                                         "ed_tecni", "ed_supe"))

data_proc$Libros_apod_rec <- factor(data_proc$Libros_apod_rec, 
                                    levels = c("Entre 0 y 10 libros",
                                               "Entre 11 y 25 libros",
                                               "Entre 26 y 100 libros",
                                               "Más de 100 libros"), 
                                    labels = c("libros1", "libros2", 
                                               "libros3", "libros4"))

data_proc$quintiles_ingresos_pc_factor <- factor(data_proc$quintiles_ingresos_pc_factor, 
                                                 levels = c("Quintil 1",
                                                            "Quintil 2",
                                                            "Quintil 3",
                                                            "Quintil 4",
                                                            "Quintil 5",
                                                            "Ns/Nr"),
                                                 labels = c("quintil1",
                                                            "quintil2",
                                                            "quintil3",
                                                            "quintil4",
                                                            "quintil5",
                                                            "quintilna"))

data_proc <- dummy_cols(data_proc, select_columns = "Educacion")
data_proc <- dummy_cols(data_proc, select_columns = "Libros_apod_rec")
data_proc <- dummy_cols(data_proc, select_columns = "quintiles_ingresos_pc_factor")
```


```{r}
reg_med_ig1 <- lme4::lmer(igualdad.pad ~ Educacion_ed_media + Educacion_ed_tecni + Educacion_ed_supe + Libros_apod_rec_libros2 + Libros_apod_rec_libros3 + Libros_apod_rec_libros4 + quintiles_ingresos_pc_factor_quintil2 + quintiles_ingresos_pc_factor_quintil3 + quintiles_ingresos_pc_factor_quintil4 + quintiles_ingresos_pc_factor_quintil5 + quintiles_ingresos_pc_factor_quintilna + REGION + dependencia + (1 | RBD), data = data_proc)

reg_out_ig1 <- lme4::lmer(igualdad.est ~ igualdad.pad + Educacion_ed_media + Educacion_ed_tecni + Educacion_ed_supe + Libros_apod_rec_libros2 + Libros_apod_rec_libros3 + Libros_apod_rec_libros4 + quintiles_ingresos_pc_factor_quintil2 + quintiles_ingresos_pc_factor_quintil3 + quintiles_ingresos_pc_factor_quintil4 + quintiles_ingresos_pc_factor_quintil5 + quintiles_ingresos_pc_factor_quintilna + Sexo + ap_discusion + mean_discusion + num_fem + c_civic + REGION + dependencia + (1 | RBD), data=data_proc)
```

```{r}
# Educacion
set.seed(123)
med_out_iged1 <- mediate(reg_med_ig1, reg_out_ig1,
                         treat = "Educacion_ed_media", 
                         mediator = "igualdad.pad", sims = 100)
med_out_iged2 <- mediate(reg_med_ig1, reg_out_ig1,
                         treat = "Educacion_ed_tecni", 
                         mediator = "igualdad.pad", sims = 100)
med_out_iged3 <- mediate(reg_med_ig1, reg_out_ig1, 
                         treat = "Educacion_ed_supe", 
                         mediator = "igualdad.pad", sims = 100)
summary(med_out_iged1)
summary(med_out_iged2)
summary(med_out_iged3)
```


```{r}
# Libros
med_out_iglib1 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "Libros_apod_rec_libros2", 
                          mediator = "igualdad.pad", sims = 100)
med_out_iglib2 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "Libros_apod_rec_libros3", 
                          mediator = "igualdad.pad", sims = 100)
med_out_iglib3 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "Libros_apod_rec_libros4",
                          mediator = "igualdad.pad", sims = 100)
summary(med_out_iglib1)
summary(med_out_iglib2)
summary(med_out_iglib3)
```

```{r}
# Ingresos
med_out_iging1 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "quintiles_ingresos_pc_factor_quintil2", 
                          mediator = "igualdad.pad", sims = 100)
med_out_iging2 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "quintiles_ingresos_pc_factor_quintil3", 
                          mediator = "igualdad.pad", sims = 100)
med_out_iging3 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "quintiles_ingresos_pc_factor_quintil4", 
                          mediator = "igualdad.pad", sims = 100)
med_out_iging4 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "quintiles_ingresos_pc_factor_quintil5", 
                          mediator = "igualdad.pad", sims = 100)
med_out_iging5 <- mediate(reg_med_ig1, reg_out_ig1, 
                          treat = "quintiles_ingresos_pc_factor_quintilna", 
                          mediator = "igualdad.pad", sims = 100)
summary(med_out_iging1)
summary(med_out_iging2)
summary(med_out_iging3)
summary(med_out_iging4)
summary(med_out_iging5)
```

#### Espacio público
```{r}
reg_med_pub1 <- lme4::lmer(esp_publico.pad ~ Educacion_ed_media + Educacion_ed_tecni + Educacion_ed_supe + Libros_apod_rec_libros2 + Libros_apod_rec_libros3 + Libros_apod_rec_libros4 + quintiles_ingresos_pc_factor_quintil2 + quintiles_ingresos_pc_factor_quintil3 + quintiles_ingresos_pc_factor_quintil4 + quintiles_ingresos_pc_factor_quintil5 + quintiles_ingresos_pc_factor_quintilna + REGION + dependencia + (1 | RBD), data = data_proc)

reg_out_pub1 <- lme4::lmer(esp_publico.est ~ esp_publico.pad + Educacion_ed_media + Educacion_ed_tecni + Educacion_ed_supe + Libros_apod_rec_libros2 + Libros_apod_rec_libros3 + Libros_apod_rec_libros4 + quintiles_ingresos_pc_factor_quintil2 + quintiles_ingresos_pc_factor_quintil3 + quintiles_ingresos_pc_factor_quintil4 + quintiles_ingresos_pc_factor_quintil5 + quintiles_ingresos_pc_factor_quintilna + Sexo + ap_discusion + mean_discusion + num_fem + c_civic + REGION + dependencia + (1 | RBD), data=data_proc)
```

```{r}
# Educacion
med_out_pubed1 <- mediate(reg_med_pub1, reg_out_pub1, 
                          treat = "Educacion_ed_media", 
                          mediator = "esp_publico.pad", sims = 100)
med_out_pubed2 <- mediate(reg_med_pub1, reg_out_pub1, 
                          treat = "Educacion_ed_tecni", 
                          mediator = "esp_publico.pad", sims = 100)
med_out_pubed3 <- mediate(reg_med_pub1, reg_out_pub1, 
                          treat = "Educacion_ed_supe", 
                          mediator = "esp_publico.pad", sims = 100)
summary(med_out_pubed1)
summary(med_out_pubed2)
summary(med_out_pubed3)
```
```{r}
# Libros
med_out_publib1 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "Libros_apod_rec_libros2", 
                           mediator = "esp_publico.pad", sims = 100)
med_out_publib2 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "Libros_apod_rec_libros3",
                           mediator = "esp_publico.pad", sims = 100)
med_out_publib3 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "Libros_apod_rec_libros4",
                           mediator = "esp_publico.pad", sims = 100)

summary(med_out_publib1)
summary(med_out_publib2)
summary(med_out_publib3)
```

```{r}
# Ingresos
med_out_pubing1 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "quintiles_ingresos_pc_factor_quintil2", 
                           mediator = "esp_publico.pad", sims = 100)
med_out_pubing2 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "quintiles_ingresos_pc_factor_quintil3", 
                           mediator = "esp_publico.pad", sims = 100)
med_out_pubing3 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "quintiles_ingresos_pc_factor_quintil4", 
                           mediator = "esp_publico.pad", sims = 100)
med_out_pubing4 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "quintiles_ingresos_pc_factor_quintil5", 
                           mediator = "esp_publico.pad", sims = 100)
med_out_pubing5 <- mediate(reg_med_pub1, reg_out_pub1, 
                           treat = "quintiles_ingresos_pc_factor_quintilna", 
                           mediator = "esp_publico.pad", sims = 100)
summary(med_out_pubing1)
summary(med_out_pubing2)
summary(med_out_pubing3)
summary(med_out_pubing4)
summary(med_out_pubing5)
```

#### Espacio privado
```{r}
reg_med_priv1 <- lme4::lmer(esp_privado.pad ~ Educacion_ed_media + Educacion_ed_tecni + Educacion_ed_supe + Libros_apod_rec_libros2 + Libros_apod_rec_libros3 + Libros_apod_rec_libros4 + quintiles_ingresos_pc_factor_quintil2 + quintiles_ingresos_pc_factor_quintil3 + quintiles_ingresos_pc_factor_quintil4 + quintiles_ingresos_pc_factor_quintil5 + quintiles_ingresos_pc_factor_quintilna + REGION + dependencia + (1 | RBD), data = data_proc)

reg_out_priv1 <- lme4::lmer(esp_privado.est ~ esp_privado.pad + Educacion_ed_media + Educacion_ed_tecni + Educacion_ed_supe + Libros_apod_rec_libros2 + Libros_apod_rec_libros3 + Libros_apod_rec_libros4 + quintiles_ingresos_pc_factor_quintil2 + quintiles_ingresos_pc_factor_quintil3 + quintiles_ingresos_pc_factor_quintil4 + quintiles_ingresos_pc_factor_quintil5 + quintiles_ingresos_pc_factor_quintilna + Sexo + ap_discusion + mean_discusion + num_fem + c_civic + REGION + dependencia + (1 | RBD), data=data_proc)
```

```{r}
# Educacion
med_out_prived1 <- mediate(reg_med_priv1, reg_out_priv1, 
                           treat = "Educacion_ed_media", 
                           mediator = "esp_privado.pad", sims = 100)
med_out_prived2 <- mediate(reg_med_priv1, reg_out_priv1, 
                           treat = "Educacion_ed_tecni", 
                           mediator = "esp_privado.pad", sims = 100)
med_out_prived3 <- mediate(reg_med_priv1, reg_out_priv1, 
                           treat = "Educacion_ed_supe", 
                           mediator = "esp_privado.pad", sims = 100)
summary(med_out_prived1)
summary(med_out_prived2)
summary(med_out_prived3)
```

```{r}
# Libros
med_out_privlib1 <- mediate(reg_med_priv1, reg_out_priv1, 
                            treat = "Libros_apod_rec_libros2", 
                            mediator = "esp_privado.pad", sims = 100)
med_out_privlib2 <- mediate(reg_med_priv1, reg_out_priv1, 
                            treat = "Libros_apod_rec_libros3",
                            mediator = "esp_privado.pad", sims = 100)
med_out_privlib3 <- mediate(reg_med_priv1, reg_out_priv1, 
                            treat = "Libros_apod_rec_libros4", 
                            mediator = "esp_privado.pad", sims = 100)

summary(med_out_privlib1)
summary(med_out_privlib2)
summary(med_out_privlib3)
```

```{r}
# Ingresos
med_out_priving1 <- mediate(reg_med_priv1, reg_out_priv1,
                            treat = "quintiles_ingresos_pc_factor_quintil2", 
                            mediator = "esp_privado.pad", sims = 100)
med_out_priving2 <- mediate(reg_med_priv1, reg_out_priv1, 
                            treat = "quintiles_ingresos_pc_factor_quintil3", 
                            mediator = "esp_privado.pad", sims = 100)
med_out_priving3 <- mediate(reg_med_priv1, reg_out_priv1, 
                            treat = "quintiles_ingresos_pc_factor_quintil4", 
                            mediator = "esp_privado.pad", sims = 100)
med_out_priving4 <- mediate(reg_med_priv1, reg_out_priv1, 
                            treat = "quintiles_ingresos_pc_factor_quintil5", 
                            mediator = "esp_privado.pad", sims = 100)
med_out_priving5 <- mediate(reg_med_priv1, reg_out_priv1, 
                            treat = "quintiles_ingresos_pc_factor_quintilna", 
                            mediator = "esp_privado.pad", sims = 100)

summary(med_out_priving1)
summary(med_out_priving2)
summary(med_out_priving3)
summary(med_out_priving4)
summary(med_out_priving5)
```

```{r}
summary(med_out_iged1)
med_out_iged1[["z0"]]       # DIRECTO
med_out_iged1[["d0"]]       # INDIRECTO
med_out_iged1[["tau.coef"]] # TOTAL
med_out_iged1[["n.avg"]]    # Proporcion de INDIRECTO del TOTAL
med_out_iged1[["d0"]]/med_out_iged1[["tau.coef"]] 
```

### Tabla mediación mediate

```{r}
# -------------------------------------------------------------------------
directos.DV1 = 
  c(paste0(round(med_out_iged1[["z0"]],3), stars.pval(med_out_iged1[["z0.p"]])),
    paste0(round(med_out_iged2[["z0"]],3), stars.pval(med_out_iged2[["z0.p"]])),
    paste0(round(med_out_iged3[["z0"]],3), stars.pval(med_out_iged3[["z0.p"]])),
    paste0(round(med_out_iglib1[["z0"]],3),stars.pval(med_out_iglib1[["z0.p"]])),
    paste0(round(med_out_iglib2[["z0"]],3),stars.pval(med_out_iglib2[["z0.p"]])),
    paste0(round(med_out_iglib3[["z0"]],3),stars.pval(med_out_iglib3[["z0.p"]])),
    paste0(round(med_out_iging1[["z0"]],3),stars.pval(med_out_iging1[["z0.p"]])),
    paste0(round(med_out_iging2[["z0"]],3),stars.pval(med_out_iging2[["z0.p"]])),
    paste0(round(med_out_iging3[["z0"]],3),stars.pval(med_out_iging3[["z0.p"]])),
    paste0(round(med_out_iging4[["z0"]],3),stars.pval(med_out_iging4[["z0.p"]])),
    paste0(round(med_out_iging5[["z0"]],3),stars.pval(med_out_iging5[["z0.p"]])))
indirecto.DV1 = 
  c(paste0(round(med_out_iged1[["d0"]],3), stars.pval(med_out_iged1[["d0.p"]])),
    paste0(round(med_out_iged2[["d0"]],3), stars.pval(med_out_iged2[["d0.p"]])),
    paste0(round(med_out_iged3[["d0"]],3), stars.pval(med_out_iged3[["d0.p"]])),
    paste0(round(med_out_iglib1[["d0"]],3),stars.pval(med_out_iglib1[["d0.p"]])),
    paste0(round(med_out_iglib2[["d0"]],3),stars.pval(med_out_iglib2[["d0.p"]])),
    paste0(round(med_out_iglib3[["d0"]],3),stars.pval(med_out_iglib3[["d0.p"]])),
    paste0(round(med_out_iging1[["d0"]],3),stars.pval(med_out_iging1[["d0.p"]])),
    paste0(round(med_out_iging2[["d0"]],3),stars.pval(med_out_iging2[["d0.p"]])),
    paste0(round(med_out_iging3[["d0"]],3),stars.pval(med_out_iging3[["d0.p"]])),
    paste0(round(med_out_iging4[["d0"]],3),stars.pval(med_out_iging4[["d0.p"]])),
    paste0(round(med_out_iging5[["d0"]],3),stars.pval(med_out_iging5[["d0.p"]])))
totales.DV1 =
  c(paste0(round(med_out_iged1[["tau.coef"]],3), stars.pval(med_out_iged1[["tau.p"]])),
    paste0(round(med_out_iged2[["tau.coef"]],3), stars.pval(med_out_iged2[["tau.p"]])),
    paste0(round(med_out_iged3[["tau.coef"]],3), stars.pval(med_out_iged3[["tau.p"]])),
    paste0(round(med_out_iglib1[["tau.coef"]],3),stars.pval(med_out_iglib1[["tau.p"]])),
    paste0(round(med_out_iglib2[["tau.coef"]],3),stars.pval(med_out_iglib2[["tau.p"]])),
    paste0(round(med_out_iglib3[["tau.coef"]],3),stars.pval(med_out_iglib3[["tau.p"]])),
    paste0(round(med_out_iging1[["tau.coef"]],3),stars.pval(med_out_iging1[["tau.p"]])),
    paste0(round(med_out_iging2[["tau.coef"]],3),stars.pval(med_out_iging2[["tau.p"]])),
    paste0(round(med_out_iging3[["tau.coef"]],3),stars.pval(med_out_iging3[["tau.p"]])),
    paste0(round(med_out_iging4[["tau.coef"]],3),stars.pval(med_out_iging4[["tau.p"]])),
    paste0(round(med_out_iging5[["tau.coef"]],3),stars.pval(med_out_iging5[["tau.p"]])))
pct_ind.DV1 =
  c(paste0(round(med_out_iged1[["n.avg"]]*100,2),"%"), 
    paste0(round(med_out_iged2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iged3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iglib1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iglib2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iglib3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iging1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iging2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iging3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iging4[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_iging5[["n.avg"]]*100,2),"%"))
```

```{r}
# -------------------------------------------------------------------------
directos.DV2 = 
  c(paste0(round(med_out_pubed1[["z0"]],3),stars.pval(med_out_pubed1[["z0.p"]])),
    paste0(round(med_out_pubed2[["z0"]],3),stars.pval(med_out_pubed2[["z0.p"]])),
    paste0(round(med_out_pubed3[["z0"]],3),stars.pval(med_out_pubed3[["z0.p"]])),
    paste0(round(med_out_publib1[["z0"]],3),stars.pval(med_out_publib1[["z0.p"]])),
    paste0(round(med_out_publib2[["z0"]],3),stars.pval(med_out_publib2[["z0.p"]])),
    paste0(round(med_out_publib3[["z0"]],3),stars.pval(med_out_publib3[["z0.p"]])),
    paste0(round(med_out_pubing1[["z0"]],3),stars.pval(med_out_pubing1[["z0.p"]])),
    paste0(round(med_out_pubing2[["z0"]],3),stars.pval(med_out_pubing2[["z0.p"]])),
    paste0(round(med_out_pubing3[["z0"]],3),stars.pval(med_out_pubing3[["z0.p"]])),
    paste0(round(med_out_pubing4[["z0"]],3),stars.pval(med_out_pubing4[["z0.p"]])),
    paste0(round(med_out_pubing5[["z0"]],3),stars.pval(med_out_pubing5[["z0.p"]])))
indirecto.DV2 = 
  c(paste0(round(med_out_pubed1[["d0"]],3),stars.pval(med_out_pubed1[["d0.p"]])),
    paste0(round(med_out_pubed2[["d0"]],3),stars.pval(med_out_pubed2[["d0.p"]])),
    paste0(round(med_out_pubed3[["d0"]],3),stars.pval(med_out_pubed3[["d0.p"]])),
    paste0(round(med_out_publib1[["d0"]],3),stars.pval(med_out_publib1[["d0.p"]])),
    paste0(round(med_out_publib2[["d0"]],3),stars.pval(med_out_publib2[["d0.p"]])),
    paste0(round(med_out_publib3[["d0"]],3),stars.pval(med_out_publib3[["d0.p"]])),
    paste0(round(med_out_pubing1[["d0"]],3),stars.pval(med_out_pubing1[["d0.p"]])),
    paste0(round(med_out_pubing2[["d0"]],3),stars.pval(med_out_pubing2[["d0.p"]])),
    paste0(round(med_out_pubing3[["d0"]],3),stars.pval(med_out_pubing3[["d0.p"]])),
    paste0(round(med_out_pubing4[["d0"]],3),stars.pval(med_out_pubing4[["d0.p"]])),
    paste0(round(med_out_pubing5[["d0"]],3),stars.pval(med_out_pubing5[["d0.p"]])))
totales.DV2 = 
  c(paste0(round(med_out_pubed1[["tau.coef"]],3),stars.pval(med_out_pubed1[["tau.p"]])),
    paste0(round(med_out_pubed2[["tau.coef"]],3),stars.pval(med_out_pubed2[["tau.p"]])),
    paste0(round(med_out_pubed3[["tau.coef"]],3),stars.pval(med_out_pubed3[["tau.p"]])),
    paste0(round(med_out_publib1[["tau.coef"]],3),stars.pval(med_out_publib1[["tau.p"]])),
    paste0(round(med_out_publib2[["tau.coef"]],3),stars.pval(med_out_publib2[["tau.p"]])),
    paste0(round(med_out_publib3[["tau.coef"]],3),stars.pval(med_out_publib3[["tau.p"]])),
    paste0(round(med_out_pubing1[["tau.coef"]],3),stars.pval(med_out_pubing1[["tau.p"]])),
    paste0(round(med_out_pubing2[["tau.coef"]],3),stars.pval(med_out_pubing2[["tau.p"]])),
    paste0(round(med_out_pubing3[["tau.coef"]],3),stars.pval(med_out_pubing3[["tau.p"]])),
    paste0(round(med_out_pubing4[["tau.coef"]],3),stars.pval(med_out_pubing4[["tau.p"]])),
    paste0(round(med_out_pubing5[["tau.coef"]],3),stars.pval(med_out_pubing5[["tau.p"]])))
pct_ind.DV2 = 
  c(paste0(round(med_out_pubed1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_pubed2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_pubed3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_publib1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_publib2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_publib3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_pubing1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_pubing2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_pubing3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_pubing4[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_pubing5[["n.avg"]]*100,2),"%"))
```


```{r}
# -------------------------------------------------------------------------
directos.DV3 = 
  c(paste0(round(med_out_prived1[["z0"]],3),stars.pval(med_out_prived1[["z0.p"]])),
    paste0(round(med_out_prived2[["z0"]],3),stars.pval(med_out_prived2[["z0.p"]])),
    paste0(round(med_out_prived3[["z0"]],3),stars.pval(med_out_prived3[["z0.p"]])),
    paste0(round(med_out_privlib1[["z0"]],3),stars.pval(med_out_privlib1[["z0.p"]])),
    paste0(round(med_out_privlib2[["z0"]],3),stars.pval(med_out_privlib2[["z0.p"]])),
    paste0(round(med_out_privlib3[["z0"]],3),stars.pval(med_out_privlib3[["z0.p"]])),
    paste0(round(med_out_priving1[["z0"]],3),stars.pval(med_out_priving1[["z0.p"]])),
    paste0(round(med_out_priving2[["z0"]],3),stars.pval(med_out_priving2[["z0.p"]])),
    paste0(round(med_out_priving3[["z0"]],3),stars.pval(med_out_priving3[["z0.p"]])),
    paste0(round(med_out_priving4[["z0"]],3),stars.pval(med_out_priving4[["z0.p"]])),
    paste0(round(med_out_priving5[["z0"]],3),stars.pval(med_out_priving5[["z0.p"]])))
indirecto.DV3 = 
  c(paste0(round(med_out_prived1[["d0"]],3),stars.pval(med_out_prived1[["d0.p"]])),
    paste0(round(med_out_prived2[["d0"]],3),stars.pval(med_out_prived2[["d0.p"]])),
    paste0(round(med_out_prived3[["d0"]],3),stars.pval(med_out_prived3[["d0.p"]])),
    paste0(round(med_out_privlib1[["d0"]],3),stars.pval(med_out_privlib1[["d0.p"]])),
    paste0(round(med_out_privlib2[["d0"]],3),stars.pval(med_out_privlib2[["d0.p"]])),
    paste0(round(med_out_privlib3[["d0"]],3),stars.pval(med_out_privlib3[["d0.p"]])),
    paste0(round(med_out_priving1[["d0"]],3),stars.pval(med_out_priving1[["d0.p"]])),
    paste0(round(med_out_priving2[["d0"]],3),stars.pval(med_out_priving2[["d0.p"]])),
    paste0(round(med_out_priving3[["d0"]],3),stars.pval(med_out_priving3[["d0.p"]])),
    paste0(round(med_out_priving4[["d0"]],3),stars.pval(med_out_priving4[["d0.p"]])),
    paste0(round(med_out_priving5[["d0"]],3),stars.pval(med_out_priving5[["d0.p"]])))
totales.DV3 = 
  c(paste0(round(med_out_prived1[["tau.coef"]],3),stars.pval(med_out_prived1[["tau.p"]])),
    paste0(round(med_out_prived2[["tau.coef"]],3),stars.pval(med_out_prived2[["tau.p"]])),
    paste0(round(med_out_prived3[["tau.coef"]],3),stars.pval(med_out_prived3[["tau.p"]])),
    paste0(round(med_out_privlib1[["tau.coef"]],3),stars.pval(med_out_privlib1[["tau.p"]])),
    paste0(round(med_out_privlib2[["tau.coef"]],3),stars.pval(med_out_privlib2[["tau.p"]])),
    paste0(round(med_out_privlib3[["tau.coef"]],3),stars.pval(med_out_privlib3[["tau.p"]])),
    paste0(round(med_out_priving1[["tau.coef"]],3),stars.pval(med_out_priving1[["tau.p"]])),
    paste0(round(med_out_priving2[["tau.coef"]],3),stars.pval(med_out_priving2[["tau.p"]])),
    paste0(round(med_out_priving3[["tau.coef"]],3),stars.pval(med_out_priving3[["tau.p"]])),
    paste0(round(med_out_priving4[["tau.coef"]],3),stars.pval(med_out_priving4[["tau.p"]])),
    paste0(round(med_out_priving5[["tau.coef"]],3),stars.pval(med_out_priving5[["tau.p"]])))
pct_ind.DV3 = 
  c(paste0(round(med_out_prived1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_prived2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_prived3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_privlib1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_privlib2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_privlib3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_priving1[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_priving2[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_priving3[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_priving4[["n.avg"]]*100,2),"%"),
    paste0(round(med_out_priving5[["n.avg"]]*100,2),"%"))
```

```{r}
collapse_rows_dt2 <-
  data.frame(vars = c(rep("Educación de los padres", 3),
                    rep("Cantidad de libros", 3),
                    rep("Quintiles de ingreso", 5)),
           catego = c(sjlabelled::get_labels(data$Educacion)[-1],
                      sjlabelled::get_labels(data$Libros_apod_rec)[-1],
                      sjlabelled::get_labels(data$quintiles_ingresos_pc_factor)[-1]),
           directos.DV1,indirecto.DV1,totales.DV1,pct_ind.DV1, #derechos y oport
           directos.DV2,indirecto.DV2,totales.DV2,pct_ind.DV2, #espacio publico
           directos.DV3,indirecto.DV3,totales.DV3,pct_ind.DV3) #espacio privado
```

```{r echo=TRUE, include=TRUE}
kbl(collapse_rows_dt2, 
    align = "c", 
    col.names =  c("Variable",
                   "Categorías", 
                   "Efectos Directos", "Efectos Indirectos", "Efectos Totales",
                   "% de Efectos Indirectos", 
                   "Efectos Directos", "Efectos Indirectos", "Efectos Totales", 
                   "% de Efectos Indirectos", 
                   "Efectos Directos", "Efectos Indirectos", "Efectos Totales",
                   "% de Efectos Indirectos")) %>%
  add_header_above(c(" " = 2,
                     "Actitudes hacia  la igualdad de derechos y oportunidades"=4, 
                     "Actitudes hacia la distribución igualitaria de roles en la esfera pública"=4, 
                     "Actitudes hacia la distribución igualitaria de roles en la esfera privada"=4), 
                   bold = T)%>%  
  kable_paper("hover",full_width = F) %>%
     column_spec(1, bold = T) %>%
     collapse_rows(columns = 1:2, valign = "top")
```
