---
title: "preparacion"
author: "Anais Herrera Leighton"
date: "18-01-2021"
output: html_document
---

```{r}
library(haven)
```

```{r}
apod_data <- haven::read_dta(file = url("https://github.com/formacionciudadana/data-paces/blob/main/docs/paces/data/base_apoderadosv2.dta?raw=true"))
est_data <- haven::read_dta(file = url("https://github.com/formacionciudadana/data-paces/blob/main/docs/paces/data/base_estudiantesv2.dta?raw=true"))
```
# Recursos de la familia
## Nivel educacional de los padres
```{r}
# Respuestas apoderado/a
apod_data$P45[apod_data$P45==9]<-NA 
apod_data$edpad <- factor(apod_data$P45, levels = c(1,2,3,4), labels = c("8vo básico o menos", "Educación media", "Educación Técnica superior (IP o CFT)", "Una carrera en la Universidad o estudios de posgrado"))

# Respuestas estudiantes
est_data$P66[est_data$P66==8]<-NA #ed. madre
est_data$P66[est_data$P66==9]<-NA
est_data$P67[est_data$P67==8]<-NA #ed. padre
est_data$P67[est_data$P67==9]<-NA
est_data$edpadres <- ifelse(est_data$P66>est_data$P67,est_data$P66,est_data$P67)
est_data$edpad <- factor(est_data$edpadres, levels = c(1,2,3,4,5), labels = c("No completó 8vo básico", "8vo básico", "Educación media", "Educación Técnica superior (IP o CFT)", "Una carrera en la Universidad o estudios de posgrado"))
```

